version: '3.8'

services:
    web-app:
        image: competitor-matching-web-app/web-app:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5173:5173'
        env_file:
            - ./.env
