---
version: '3.8'

services:
    web-app:
        image: competitor-matching-web-app/web-app:latest
        build:
            context: ../
            dockerfile: docker/Dockerfile
        ports:
            - '8080:80'
        environment:
            - VITE_APP_ENV=production
        env_file:
            - ../.env
